Repository ContainerSolutions/externalsecret-operator, pull requests merged in 2020-11, with the labels that each got.

#124 Improved readability, fixed typo and replaced old links
  CONTRIBUTING.md
  README.md
Labels: invalid

#131 Gitlab backend
  README.md
  config/credentials/credentials-gitlab.yaml
  config/credentials/kustomization.yaml
  config/samples/store_v1alpha1_secretstore.yaml
  go.mod
  go.sum
  pkg/gitlab/backend.go
  pkg/register/register.go
  pkg/register/register_test.go
Labels: backend/all

#137 docs: split backends readmes
  README.md
  docs/backends/gitlab.md
  docs/backends/gsm.md
Labels: merge

#138 remove outdated TOC items
  README.md
Labels: merge
